name:Continuous Integration
on:
  push:
    branches:["main"]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: check project files
        run: | 
          echo "running CI process..."
          ls -la
      - name: validate HTML
       run: |
         test -f index.html
         echo"HTML file exits"
      - name: CI success
        run: echo "build and validation completed successfully"
